export const CLIP_INDEX_PATH = 'clips/README.md';
export const CLIP_INDEX_MARKER = '<!-- generated by reading-clipper; do not edit -->';

export interface ClipIndexEntry {
  path: string;
  title: string;
  url: string | null;
  clippedAt: string;
}

/** 名前だけでは手書きREADMEや過去の記事と区別できないため、所有マーカーまで見る。 */
export function isGeneratedClipIndex(path: string, content: string): boolean {
  return path === CLIP_INDEX_PATH && content.includes(CLIP_INDEX_MARKER);
}

/** GitHubのREADMEで壊さない文字だけを残し、改行を1行へ畳む。 */
function markdownLabel(value: string): string {
  return value.replace(/\s+/gu, ' ').trim().replace(/([\\\[\]])/gu, '\\$1');
}

function sourceHref(url: string | null): string | null {
  if (!url) return null;
  try {
    const parsed = new URL(url);
    return parsed.protocol === 'http:' || parsed.protocol === 'https:' ? parsed.href : null;
  } catch {
    return null;
  }
}

function clipHost(url: string | null): string {
  if (!url) return '';
  try {
    return new URL(url).hostname;
  } catch {
    return '';
  }
}

/** `clipped_at`をJSTの短い日付にする。 */
function clippedDay(clippedAt: string): string {
  const at = new Date(clippedAt);
  if (Number.isNaN(at.getTime())) return '';
  const jst = new Date(at.getTime() + 9 * 60 * 60 * 1000);
  return `${jst.getUTCMonth() + 1}/${jst.getUTCDate()}`;
}

export function renderClipIndex(entries: ClipIndexEntry[]): string {
  const heading = `${CLIP_INDEX_MARKER}\n# Clips\n\n最近追加した20件を、新しい順に表示している。\n\n`;
  if (entries.length === 0) return `${heading}まだクリップはない。\n`;

  const rows = entries.map((entry) => {
    const label = markdownLabel(entry.title);
    const href = sourceHref(entry.url);
    const link = href ? `[${label}](<${href}>)` : label;
    return `- ${[clippedDay(entry.clippedAt), link, clipHost(entry.url)].filter(Boolean).join(' · ')}`;
  });
  return `${heading}${rows.join('\n')}\n`;
}
