export const CLIP_INDEX_PATH = 'clips/README.md';
export const CLIP_INDEX_MARKER = '<!-- generated by reading-clipper; do not edit -->';

/** カードで出す件数。残りは箇条書きへ落とす（ADR 0023）。 */
const CARD_CLIP_SIZE = 5;

/** サムネイルの幅。GitHubが`max-width`を足すので、狭い画面でも溢れない。 */
const CARD_IMAGE_WIDTH = 320;

export interface ClipIndexEntry {
  path: string;
  title: string;
  url: string | null;
  excerpt: string | null;
  imageUrl: string | null;
  clippedAt: string;
  /** 片付けた印。カードへ出すか箇条書きで消すかを、これだけで決める。 */
  dismissedAt: string | null;
}

/** 見出しに出す全体の量。`countClips`の戻り値をそのまま渡す。 */
export interface ClipIndexCounts {
  total: number;
  undismissed: number;
}

/** 名前だけでは手書きREADMEや過去の記事と区別できないため、所有マーカーまで見る。 */
export function isGeneratedClipIndex(path: string, content: string): boolean {
  return path === CLIP_INDEX_PATH && content.includes(CLIP_INDEX_MARKER);
}

/**
 * GitHubがMarkdownとして解釈する文字を殺す。
 *
 * 目的は表示崩れを防ぐことであって、安全ではない。GitHubのサニタイザは`<script>`や
 * `onerror`を落とすが、`<b>`のような無害なタグは素通りさせる。抜粋は記事本文から
 * 作るのでHTMLが混じることがあり、そのまま埋めるとカードの見た目が記事ごとに変わる。
 */
function escapeHtml(value: string): string {
  return value
    .replace(/&/gu, '&amp;')
    .replace(/</gu, '&lt;')
    .replace(/>/gu, '&gt;')
    .replace(/"/gu, '&quot;');
}

/** GitHubのREADMEで壊さない文字だけを残し、改行を1行へ畳む。 */
function markdownLabel(value: string): string {
  return value.replace(/\s+/gu, ' ').trim().replace(/([\\\[\]])/gu, '\\$1');
}

function sourceHref(url: string | null): string | null {
  if (!url) return null;
  try {
    const parsed = new URL(url);
    return parsed.protocol === 'http:' || parsed.protocol === 'https:' ? parsed.href : null;
  } catch {
    return null;
  }
}

function clipHost(url: string | null): string {
  if (!url) return '';
  try {
    return new URL(url).hostname;
  } catch {
    return '';
  }
}

/** `clipped_at`をJSTの短い日付にする。 */
function clippedDay(clippedAt: string): string {
  const at = new Date(clippedAt);
  if (Number.isNaN(at.getTime())) return '';
  const jst = new Date(at.getTime() + 9 * 60 * 60 * 1000);
  return `${jst.getUTCMonth() + 1}/${jst.getUTCDate()}`;
}

/** `clips/README.md`から同じディレクトリの保存済みMarkdownへ移動する相対リンク。 */
function savedCopyHref(path: string): string {
  const relativePath = path.startsWith('clips/') ? path.slice('clips/'.length) : path;
  return `./${relativePath.split('/').map(encodeURIComponent).join('/')}`;
}

/** 題名。URLが無い、または不正な古いデータはリンクにしない（ADR 0017）。 */
function titleLink(entry: ClipIndexEntry): string {
  const label = escapeHtml(markdownLabel(entry.title));
  const href = sourceHref(entry.url);
  return href ? `[${label}](<${href}>)` : label;
}

/**
 * カード1件。サムネイル、題名、抜粋、メタを縦に積む。
 *
 * 画像とテキストを横へ並べるにはHTMLの表が要るが、GitHubは表の各セルへ罫線を引くので、
 * カードのつもりのものがマス目に見える。画像を持たない記事では空のセルまで残る。
 * 縦に積めば表そのものが要らず、画像が無い記事は行を1つ落とすだけで済む（ADR 0023）。
 */
function card(entry: ClipIndexEntry): string {
  const image = sourceHref(entry.imageUrl);
  const host = clipHost(entry.url);
  // 区切りは箇条書きと同じ`·`にする。同じ意味のものを2種類の記号で書き分けない。
  const saved = `[GitHub版](<${savedCopyHref(entry.path)}>)`;
  const meta = [host ? `\`${host}\`` : '', clippedDay(entry.clippedAt), saved]
    .filter(Boolean)
    .join(' · ');
  const lines: string[] = [];
  if (image) lines.push(`<img src="${escapeHtml(image)}" width="${CARD_IMAGE_WIDTH}" alt="">`);
  lines.push(`**${titleLink(entry)}**`);
  if (entry.excerpt) lines.push(escapeHtml(entry.excerpt));
  if (meta) lines.push(meta);
  return lines.join('\n\n');
}

/** 箇条書き1件。片付けたものは取り消し線で消す（ADR 0023）。 */
function listRow(entry: ClipIndexEntry): string {
  const link = titleLink(entry);
  const label = entry.dismissedAt ? `~~${link}~~` : link;
  const saved = `[GitHub版](<${savedCopyHref(entry.path)}>)`;
  return `- ${[clippedDay(entry.clippedAt), label, clipHost(entry.url), saved].filter(Boolean).join(' · ')}`;
}

export function renderClipIndex(entries: ClipIndexEntry[], counts: ClipIndexCounts): string {
  const heading =
    `${CLIP_INDEX_MARKER}\n# Clips\n\n` +
    `保存 ${counts.total}件 · まだ片付けていない ${counts.undismissed}件\n\n`;
  if (entries.length === 0) return `${heading}まだクリップはない。\n`;

  // カードは「これから読むかもしれないもの」の枠なので、片付けたものには使わない。
  // 落としたぶんは後ろのクリップが繰り上がる（ADR 0023）。
  const cards: ClipIndexEntry[] = [];
  const rest: ClipIndexEntry[] = [];
  for (const entry of entries) {
    const toCard = entry.dismissedAt === null && cards.length < CARD_CLIP_SIZE;
    (toCard ? cards : rest).push(entry);
  }

  const sections: string[] = [];
  if (cards.length > 0) {
    sections.push(`## 最近のクリップ\n\n${cards.map(card).join('\n\n')}\n`);
  }
  if (rest.length > 0) {
    // 「それ以前」はカードとの対比で意味を持つ語なので、相手がいなければ見出しを出さない。
    const listHeading = cards.length > 0 ? '## それ以前\n\n' : '';
    sections.push(`${listHeading}${rest.map(listRow).join('\n')}\n`);
  }
  return `${heading}${sections.join('\n')}`;
}
